apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: how-to-kubernetes-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx-external
  rules:
  - host: "foo.bar.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: how-to-kubernetes-service
            port:
              number: 8080