apiVersion: v1
kind: Service
metadata:
  name: how-to-kubernetes-service
  namespace: how-to-kubernetes
spec:
  selector:
    app.kubernetes.io/name: how-to-kubernetes
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080